<?php
/**
 * AppInvite model – single-use registration invite codes.
 *
 * AppInvite codes are required to create a new user account (unless the admin
 * has enabled open registration via the Setting 'registration_open').
 *
 * They are distinct from group Invite tokens:
 *   AppInvite → gates *registration* (account creation)
 *   Invite    → gates *group membership* (joining an existing group)
 *
 * Code characteristics:
 *   - Format:   12-char uppercase hex (readable, e.g. "A1B2C3D4E5F6")
 *   - Lifetime: no expiry – valid until used
 *   - Reuse:    single-use (used_by is set after consumption)
 *   - Origin:   generated by an admin, or by the system on first boot
 *
 * First-boot flow:
 *   When no users exist, _maybeGenerateSetupInvite() in bootstrap.php creates
 *   a system code (created_by = NULL). This code is shown on the login page
 *   and logged to storage/app_setup.log so the operator can complete setup.
 */
class AppInvite
{
    /**
     * Generate a new invite code, persist it, and return the token string.
     *
     * @param int|null $createdBy  Admin user ID, or NULL for system-generated codes.
     * @return string  12-char uppercase hex token (e.g. "A1B2C3D4E5F6").
     */
    public static function create(?int $createdBy): string
    {
        $db    = Database::getInstance();
        // 6 random bytes → 12 hex chars → uppercased for readability
        $token = strtoupper(bin2hex(random_bytes(6)));
        $stmt  = $db->prepare(
            'INSERT INTO app_invites (token, created_by, created_at) VALUES (?, ?, NOW())'
        );
        $stmt->execute([$token, $createdBy]);
        return $token;
    }

    /**
     * Find a valid (unused) invite code.
     *
     * The token lookup is case-insensitive (stored as uppercase; input is
     * normalised with strtoupper before querying).
     *
     * @param string $token  Code entered by the user during registration.
     * @return array|null  Invite row if found and unused, null otherwise.
     */
    public static function findValid(string $token): ?array
    {
        $db   = Database::getInstance();
        $stmt = $db->prepare(
            'SELECT * FROM app_invites WHERE token = ? AND used_by IS NULL LIMIT 1'
        );
        $stmt->execute([strtoupper($token)]);
        return $stmt->fetch() ?: null;
    }

    /**
     * Consume an invite code, associating it with the newly created user.
     *
     * After this call the code is permanently retired; findValid() will
     * return null for the same token.
     *
     * @param string $token   Code being consumed.
     * @param int    $userId  ID of the user who registered with this code.
     */
    public static function markUsed(string $token, int $userId): void
    {
        $db   = Database::getInstance();
        $stmt = $db->prepare(
            'UPDATE app_invites SET used_by = ?, used_at = NOW() WHERE token = ?'
        );
        $stmt->execute([$userId, strtoupper($token)]);
    }

    /**
     * Return all invite codes visible to the given admin, newest first.
     *
     * The query returns codes created by the admin AND system-generated codes
     * (created_by IS NULL), so the first-boot setup code always appears.
     * Each row includes the email of the user who consumed the code (if any).
     *
     * @param int $adminId  The currently logged-in admin's user ID.
     * @return array<int, array>  Invite rows with an added 'used_by_email' column.
     */
    public static function forAdmin(int $adminId): array
    {
        $db   = Database::getInstance();
        $stmt = $db->prepare(
            'SELECT ai.*, u.email AS used_by_email
             FROM app_invites ai
             LEFT JOIN users u ON u.id = ai.used_by
             WHERE ai.created_by = ? OR ai.created_by IS NULL
             ORDER BY ai.created_at DESC'
        );
        $stmt->execute([$adminId]);
        return $stmt->fetchAll();
    }

    /**
     * Return true if the users table is completely empty.
     *
     * Used during bootstrap to determine whether to generate the first-boot
     * setup code, and during registration to auto-promote the first user to admin.
     */
    public static function noUsersExist(): bool
    {
        $db   = Database::getInstance();
        $stmt = $db->query('SELECT COUNT(*) FROM users');
        return (int)$stmt->fetchColumn() === 0;
    }
}
